name: api_tester
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_material_color_picker: ^1.2.0
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  oauth2: ^2.0.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/api_test_actual_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21  
  android_adaptive_icon_foreground: "assets/api_test_actual_icon.png"
  adaptive_icon_foreground: "assets/api_test_actual_icon.png"
  android_adaptive_icon_background: "#fff"
  adaptive_icon_background: "#fff"
  android_enable_round_icon: true
  adaptive_icon_maskable: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
